### PR TITLE
clarifications on roster endpoint

### PR DESCRIPTION
**Pull request by jpslav**

### CODE REVIEW

**Comment by philschatz** [comment]
closing because stale (though, I should have merged it but _someone_ didn't follow the rules in the `README.md` ; )

**Comment by jpslav** [comment]
@philschatz it looks to me like _someone_ did follow the rules.... eventually ;-)

**Comment by philschatz** [comment]
wait, did you update the body before or after my comment? I can't remember :smile:

**Comment by jpslav** [comment]
it may have been after

**Pull request closed without merging**
