### PR TITLE
add instructions for Atom validating cnxml files

### PR DESCRIPTION
**Pull request by philschatz**
Hope this helps! If you run into problems, I can update this document (and maybe it should be moved somewhere else?)

/cc @openstaxalina @reedstrm 

# [View the Rendered version Here](https://github.com/openstax/napkin-notes/blob/atom-validation/phil/atom-and-cnxml.md)

### CODE REVIEW

**Comment by philschatz** [comment]
Is there a better place this should live (& still be editable/updated by devs as the instructions change)?

**Comment by pumazi** [comment]
Looks like this is missing configuration for collxml.

**Comment by pumazi** [comment]
Why don't we make a nebuchadnezzar command to do this configuration? Maybe something like `neb config-atom`... This would likely eliminate a good portion of these instructions. And it would mean that the atom editor is using the same RNG files as neb.

**Comment by philschatz** [comment]
👍  for moving the instructions into nebakanesar . It'd be: 

`apm install linter-autocomplete-jing` and then edit `~/.atom/config.cson` 😄

**Comment by reedstrm** [comment]
Copy the manual version of this info into a README.md in the cnxml repo, please! I'll add 'how to validate w/ xsltproc' CLI instructions.

**Comment by philschatz** [comment]
[[CPT.01.05a] Install validation package in Atom](https://trello.com/c/lp9nkO8o/24-cpt-01-05a-install-validation-package-in-atom)

**Comment by philschatz** [comment]
Moved to a PR in `rhaptos.cnxmlutils` . (automating this using neb is a good idea too 😄 )

**Pull request closed without merging**
