### PR TITLE
Update reference_book_apis.md

### PR DESCRIPTION
**Pull request by philschatz**
@jpslav @nathanstitt @karenc Continuiing discussion via PR ; )

### CODE REVIEW

**Comment by nathanstitt** [comment]
If the URL lines up nicely as @philschatz says then the FE could intercept clicks on the link and convert them to BE requests for the page with the given UUID.

Should we also discuss whether as a general rule we should apply HTML modifications on the client or server?   I'm guessing that they'll be modifications that need to be made for styling like how the reading component inserts the "Splash" overlay.

I'm loosely in favor of the client doing the work because:
  1. It has a built-in query engine that's optimized and more flexible than nokogiri (or whatever BE chooses)
  2. The client is aware of the browser size and can make modifications that take that into account if needed.

**Comment by philschatz** [comment]
Adding @dak

**Comment by dak** [comment]
Still trying to catch up quick, but I'm a little hesitant to be essentially scraping our own content for data.  My first inclination is to consider adding a couple data-type attributes, although I think I'm also not fully aware of the context of this issue.

**Comment by philschatz** [comment]
closing because stale

**Pull request closed without merging**
